version: '3.8'

services:
  backend:
    image: suggest-feature-backend
    build:
      context: ./backend
    ports:
      - "8081:8081"
    environment:
      - ENV=PROD
      - MONGO_URL=mongodb://mongo:27017
      - AWS_ACCESS_KEY=your_aws_access_key
      - AWS_SECRET=your_aws_secret
      - FACEBOOK_CLIENT_ID=your_facebook_client_id
      - FACEBOOK_CLIENT_SECRET=your_facebook_client_secret
      - FACEBOOK_REDIRECT_URL=your_facebook_redirect_url
      - FROM_EMAIL=your_email
      - GOOGLE_CLIENT_ID=your_google_client_id
      - GOOGLE_CLIENT_SECRET=your_google_client_secret
      - GOOGLE_REDIRECT_URL=your_google_redirect_url
      - JWT_KEY=your_jwt_key
      - S3_ENDPOINT=your_s3_endpoint
      - S3_KEY=your_s3_key
      - S3_SECRET=your_s3_secret
      - SKIP_DOMAIN_VERIFICATION=optional_value

  admin-frontend:
    image: suggest-feature-admin
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  user-frontend:
    image: suggest-feature-portal
    build:
      context: ./frontend-portal
    ports:
      - "3001:3001"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
