name: CI/CD for Screenshot App

on:
  push:
    branches:
      - main

jobs:
  build-screenshot-app:
    name: Build screenshot-app
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    outputs:
      job_successful: ${{ steps.job_successful.outputs.job_successful }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Check for changes in directory
        id: check_changes
        run: |
          if git diff-tree --name-only --no-commit-id ${{ github.sha }} | grep -q "^screenshot-app"; then
            echo "changes_made=yes" >> "$GITHUB_ENV"
          else
            echo "changes_made=no" >> "$GITHUB_ENV"
          fi
      - name: Set up QEMU
        if: ${{env.changes_made == 'yes'}}
        uses: docker/setup-qemu-action@v2
        with:
          platforms: "arm64"
      - name: Set up Docker Buildx
        if: ${{env.changes_made == 'yes'}}
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Container Registry
        if: ${{env.changes_made == 'yes'}}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push the Docker image
        if: ${{env.changes_made == 'yes'}}
        uses: docker/build-push-action@v3
        with:
          push: true
          context: "{{defaultContext}}:screenshot-app"
          platforms: "linux/arm64"
          tags: |
            indianbond/easystartup:suggest-feature-screenshot-app-latest-arm
            indianbond/easystartup:suggest-feature-screenshot-app-${{ github.sha }}-arm
      - id: job_successful
        if: ${{env.changes_made == 'yes'}}
        run: echo "job_successful=yes" >> "$GITHUB_OUTPUT"
  update-helm-repo-screenshot-app:
    needs: [build-screenshot-app]
    name: Commit new revision in helm repo for screenshot-app
    if: ${{needs.build-screenshot-app.outputs.job_successful == 'yes'}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Helm repo
        uses: actions/checkout@v3
        with:
          repository: "easyStartup-pulse/helm-charts"
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB }}
      - name: Update screenshot-app values.yaml
        run: |
          cd charts/suggest-feature-screenshot-app/tier1
          sed -i 's|tag: "suggest-feature-screenshot-app-.*|tag: "suggest-feature-screenshot-app-'${{ github.sha }}'-arm"|' values.yaml
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add values.yaml
          git commit -m "Update values.yaml for screenshot-app"
          git push
